[package]
name = "feed"
version = "0.1.0"
authors = ["b.egorov <b.egorov@tinkoff.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "^0.12"
hyper-router = "^0.5"
futures = "0.1"
